DROP DATABASE IF EXISTS forum_db;

CREATE DATABASE IF NOT EXISTS forum_db;

USE forum_db;

CREATE TABLE forum_db.users(
user_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
login VARCHAR(30) NOT NULL UNIQUE,
password VARCHAR(30) NOT NULL,
email VARCHAR(30) NOT NULL UNIQUE,
name VARCHAR(30) NOT NULL,
age INT(3)
);

CREATE TABLE forum_db.rooms(
room_id INT  PRIMARY KEY NOT NULL AUTO_INCREMENT,
room_name VARCHAR(100)
);

CREATE TABLE forum_db.messages(
message_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
text_message VARCHAR(512),
post_date DATETIME NOT NULL,
user_id INT NOT NULL,
image LONGBLOB,
room_id INT NOT NULL,
FOREIGN KEY (user_id) REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (room_id) REFERENCES rooms (room_id) ON UPDATE CASCADE ON DELETE CASCADE
);

